keys:
  - &rkuklik age1c09etv8g7hwn0x2ftm8d6zmfne3p7f3fcpsucg0e2mcsn87cpsfsa4ha64

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *rkuklik
