keys:
  - &rkuklik age1c09etv8g7hwn0x2ftm8d6zmfne3p7f3fcpsucg0e2mcsn87cpsfsa4ha64
  - &inspiron age1dq37xljnvedz5uhwganexcy6wlg0hw9fwpfr2vqda7wmwh8k4ccsqt00e6

creation_rules:
  - path_regex: secrets/rkuklik\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *rkuklik
  - path_regex: secrets/nixos\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *inspiron
